; PlatformIO Project Configuration File
;
; Cardputer-Adv build target for M5Stack Cardputer-Adv (SKU K132-Adv).

[env:m5stack-cardputer-adv]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 1500000
monitor_speed = 115200

board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_8MB.csv

build_flags =
    -Os
    -DESP32S3
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    M5Cardputer=https://github.com/m5stack/M5Cardputer
    fastled/FastLED@^3.3.3
