; PlatformIO Project Configuration File
;
; M5Stack Cardputer / Cardputer ADV keyboard + mouse HID

[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
board_build.flash_size = 8MB
upload_speed = 921600
monitor_speed = 115200
build_flags =
    -Os
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    https://github.com/m5stack/M5Cardputer.git
